name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  shared_preferences: ^2.2.2
  provider: ^6.1.5
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/logo.jpg
  branding: assets/branding.jpg
  color_dark: "#121212"
  image_dark: assets/logo.jpg
  branding_dark: assets/branding.jpg
  android: true
  ios: true
  android_gravity: fill
  ios_content_mode: center

flutter:
  uses-material-design: true
  assets:
    - assets/logo.jpg
    - assets/branding.jpg
    - assets/quote_background.jpg
    - assets/tree.jpg
    - assets/tree2.jpg
    - assets/tree3.jpg